# Generated by Django 5.2.8 on 2025-12-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_keywords',
            field=models.JSONField(blank=True, help_text='Custom topic keywords for company-specific analysis', null=True),
        ),
    ]
