# Generated by Django 5.2.8 on 2025-12-01 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_calls', models.IntegerField(default=0)),
                ('average_call_duration', models.FloatField(blank=True, help_text='Average call duration in seconds', null=True)),
                ('average_emotional_score', models.FloatField(blank=True, help_text='Average emotional sentiment score', null=True)),
                ('positive_calls_percentage', models.FloatField(blank=True, help_text='Percentage of positive calls', null=True)),
                ('negative_calls_percentage', models.FloatField(blank=True, help_text='Percentage of negative calls', null=True)),
                ('emotional_trend', models.CharField(blank=True, choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], max_length=20, null=True)),
                ('average_behavioral_score', models.FloatField(blank=True, help_text='Overall behavioral score', null=True)),
                ('empathy_score', models.FloatField(blank=True, help_text='Average empathy score', null=True)),
                ('professionalism_score', models.FloatField(blank=True, help_text='Average professionalism score', null=True)),
                ('problem_solving_score', models.FloatField(blank=True, help_text='Average problem solving score', null=True)),
                ('behavioral_trend', models.CharField(blank=True, choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], max_length=20, null=True)),
                ('most_common_topics', models.JSONField(default=dict, help_text='Dictionary of topic names and their counts')),
                ('topic_resolution_rate', models.JSONField(default=dict, help_text='Dictionary of topic resolution rates')),
                ('performance_consistency_score', models.FloatField(blank=True, help_text='Score 0-100, higher is more consistent', null=True)),
                ('variance_from_average', models.FloatField(blank=True, help_text='Standard deviation of performance', null=True)),
                ('ranking_in_team', models.IntegerField(blank=True, help_text='Ranking position in team', null=True)),
                ('percentile_score', models.FloatField(blank=True, help_text='Percentile score 0-100', null=True)),
                ('strengths', models.JSONField(default=list, help_text='List of identified strengths')),
                ('weaknesses', models.JSONField(default=list, help_text='List of identified weaknesses')),
                ('recommendations', models.JSONField(default=list, help_text='List of coaching recommendations')),
                ('overall_rating', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('needs_improvement', 'Needs Improvement'), ('poor', 'Poor'), ('no_data', 'No Data')], max_length=20, null=True)),
                ('summary', models.TextField(blank=True, help_text='Summary of overall performance')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Report',
                'verbose_name_plural': 'Performance Reports',
                'ordering': ['-start_date', '-end_date'],
                'unique_together': {('agent', 'report_type', 'start_date', 'end_date')},
            },
        ),
    ]
