# Generated by Django 5.2.8 on 2025-12-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereport',
            name='weekly_analysis',
            field=models.JSONField(blank=True, help_text='Week-by-week analysis for monthly reports', null=True),
        ),
    ]
