# Generated by Django 5.2.8 on 2025-12-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_performancereport_weekly_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereport',
            name='ai_generated',
            field=models.BooleanField(default=False, help_text='Whether report used AI generation'),
        ),
        migrations.AddField(
            model_name='performancereport',
            name='executive_summary',
            field=models.TextField(blank=True, help_text='Brief executive summary (2-3 sentences)'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='summary',
            field=models.TextField(blank=True, help_text='Comprehensive AI-generated or rule-based performance summary'),
        ),
    ]
