"use client";

import {
  CheckCircle,
  Lightbulb,
  MessageSquare,
  TrendingUp,
} from "lucide-react";
import { CallDetail } from "./callDetailHelpers";

interface CoachingTabProps {
  call: CallDetail;
}

function renderEvidence(evidence: any): string | null {
  if (!evidence) return null;
  if (typeof evidence === "string") return evidence;
  if (typeof evidence === "object") {
    const issue = evidence.issue;
    if (issue) return (issue as string).replace(/_/g, " ");
  }
  return null;
}

export default function CoachingTab({ call }: CoachingTabProps) {
  const ct = call.coaching_tips || {};

  // Backend: { quality_status, tips: [{ tip, justification, evidence }] }
  // Or excellent: { quality_status: "excellent", message: "..." }
  const tips = ct.tips || [];
  const isExcellent = ct.quality_status === "excellent";

  // Backend: topic_analysis = { primary_topic, primary_confidence, all_topics_detected: [{ topic, confidence, evidence_count }] }
  const ta = call.topic_analysis || {};
  const allTopics = ta.all_topics_detected || [];
  const primaryTopic = ta.primary_topic;

  return (
    <div className="space-y-6">
      {/* Excellent Performance */}
      {isExcellent && (
        <div
          className="rounded-lg p-6"
          style={{
            background: "var(--background)",
            border: "1px solid rgba(16,185,129,0.3)",
          }}
        >
          <h3
            className="text-lg font-semibold mb-3 flex items-center"
            style={{ color: "var(--text-primary)" }}
          >
            <CheckCircle
              className="w-5 h-5 mr-2"
              style={{ color: "#0caf60" }}
            />
            Excellent Performance
          </h3>
          <p style={{ color: "var(--text-secondary)" }}>
            {ct.message ||
              "Great job! No significant issues were identified in this call."}
          </p>
        </div>
      )}

      {/* Coaching Tips */}
      {tips.length > 0 && (
        <div
          className="rounded-lg p-6"
          style={{
            background: "var(--background)",
            border: "1px solid rgba(245,158,11,0.2)",
          }}
        >
          <h3
            className="text-lg font-semibold mb-4 flex items-center"
            style={{ color: "var(--text-primary)" }}
          >
            <Lightbulb className="w-5 h-5 mr-2" style={{ color: "#e68a00" }} />
            Coaching Tips
          </h3>
          <div className="space-y-4">
            {tips.map((tip: any, index: number) => (
              <div
                key={index}
                className="flex items-start space-x-3 p-4 rounded-lg"
                style={{
                  background: "#ffffff",
                  border: "1px solid var(--border)",
                }}
              >
                <div className="w-10 h-10 bg-orange-50 rounded-lg flex items-center justify-center flex-shrink-0">
                  <TrendingUp
                    className="w-5 h-5"
                    style={{ color: "#e68a00" }}
                  />
                </div>
                <div className="flex-1">
                  <p
                    className="font-medium mb-1"
                    style={{ color: "var(--text-primary)" }}
                  >
                    {tip.tip}
                  </p>
                  {tip.justification && (
                    <p
                      className="text-sm mb-1"
                      style={{ color: "var(--text-secondary)" }}
                    >
                      {tip.justification}
                    </p>
                  )}
                  {renderEvidence(tip.evidence) && (
                    <p
                      className="text-xs italic"
                      style={{ color: "var(--text-tertiary)" }}
                    >
                      Evidence: &quot;{renderEvidence(tip.evidence)}&quot;
                    </p>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {!isExcellent && tips.length === 0 && (
        <div
          className="rounded-lg p-12 text-center"
          style={{
            background: "var(--background)",
            border: "1px solid var(--border)",
          }}
        >
          <p style={{ color: "var(--text-secondary)" }}>
            No coaching tips available for this call
          </p>
        </div>
      )}

      {/* Generation info */}
      {ct.generation_method && (
        <div
          className="flex items-center space-x-4 text-xs"
          style={{ color: "var(--text-tertiary)" }}
        >
          <span>
            Generated by:{" "}
            {ct.generation_method === "ai_powered"
              ? "AI (Ollama)"
              : "Heuristic Analysis"}
          </span>
          {ct.created_at && (
            <span>at {new Date(ct.created_at).toLocaleString()}</span>
          )}
        </div>
      )}

      {/* Topics Discussed */}
      {(primaryTopic || allTopics.length > 0) && (
        <div
          className="rounded-lg p-6"
          style={{
            background: "var(--background)",
            border: "1px solid var(--border)",
          }}
        >
          <h3
            className="text-lg font-semibold mb-4 flex items-center"
            style={{ color: "var(--text-primary)" }}
          >
            <MessageSquare
              className="w-5 h-5 mr-2"
              style={{ color: "var(--accent)" }}
            />
            Topics Discussed
          </h3>
          {primaryTopic && (
            <p
              className="mb-4 text-sm"
              style={{ color: "var(--text-secondary)" }}
            >
              Primary topic:{" "}
              <span
                className="font-semibold capitalize"
                style={{ color: "var(--text-primary)" }}
              >
                {primaryTopic.replace(/_/g, " ")}
              </span>{" "}
              {ta.primary_confidence && (
                <span>
                  ({(ta.primary_confidence * 100).toFixed(0)}% confidence)
                </span>
              )}
            </p>
          )}
          <div className="flex flex-wrap gap-3">
            {allTopics.map((topic: any, index: number) => (
              <div
                key={index}
                className="px-4 py-2 bg-blue-50 border border-blue-100 rounded-lg"
              >
                <span
                  className="font-medium capitalize"
                  style={{ color: "var(--accent)" }}
                >
                  {(topic.topic || "").replace(/_/g, " ")}
                </span>
                <span
                  className="text-sm ml-2"
                  style={{ color: "var(--text-secondary)" }}
                >
                  {topic.evidence_count
                    ? `(${topic.evidence_count} matches)`
                    : topic.confidence
                      ? `(${(topic.confidence * 100).toFixed(0)}%)`
                      : ""}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
