# Generated by Django 5.2.8 on 2025-11-26 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(blank=True, help_text='Call duration in seconds', null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='call_recordings/')),
                ('transcript', models.JSONField(blank=True, help_text='Full transcript of the call', null=True)),
                ('transcript_summary', models.JSONField(blank=True, help_text='Summary of the transcript', null=True)),
                ('emotional_analysis', models.JSONField(blank=True, help_text='Detailed emotional analysis', null=True)),
                ('emotional_summary', models.JSONField(blank=True, help_text='Summary of emotional analysis', null=True)),
                ('behavioral_analysis', models.JSONField(blank=True, help_text='Detailed behavioral analysis', null=True)),
                ('behavioral_summary', models.JSONField(blank=True, help_text='Summary of behavioral analysis', null=True)),
                ('coaching_tips', models.JSONField(blank=True, help_text='AI-generated coaching tips', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call',
                'verbose_name_plural': 'Calls',
                'ordering': ['-call_date'],
            },
        ),
    ]
