# Generated by Django 5.2.8 on 2025-12-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='topic_analysis',
            field=models.JSONField(blank=True, help_text='Topic analysis of the call', null=True),
        ),
    ]
