# Generated by Django 5.2.8 on 2026-04-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_call_status_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='vocal_analysis',
            field=models.JSONField(blank=True, help_text='Audio-level vocal stress and prosody analysis per utterance', null=True),
        ),
    ]
