# Generated by Django 5.2.8 on 2026-04-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_add_vocal_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='predicted_csat',
            field=models.FloatField(blank=True, help_text='Predicted CSAT score 1.0–5.0', null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='predicted_csat_label',
            field=models.CharField(blank=True, help_text='very_satisfied / satisfied / neutral / dissatisfied / very_dissatisfied', max_length=30, null=True),
        ),
    ]
