# Generated by Django 5.2.8 on 2026-04-29 22:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0005_add_predicted_csat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('agent_email', models.EmailField(help_text='Maps to MyUser.email with role=agent in the main platform.', max_length=254)),
                ('caller_id', models.CharField(default='unknown', max_length=30)),
                ('call_started_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('audio_file', models.FileField(upload_to='mock_callcenter/recordings/')),
                ('analyzed', models.BooleanField(db_index=True, default=False, help_text='Set to True once the main platform has imported and enqueued this call.')),
                ('imported_at', models.DateTimeField(blank=True, help_text='Timestamp when the main platform imported this call.', null=True)),
                ('platform_call', models.OneToOneField(blank=True, help_text='The Call record created in the main platform for this external call.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_source', to='calls.call')),
            ],
            options={
                'verbose_name': 'External Call',
                'verbose_name_plural': 'External Calls',
                'ordering': ['-call_started_at'],
            },
        ),
    ]
