# Generated by Django 5.2.8 on 2025-11-25 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0002_myuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='company.company'),
        ),
    ]
